services:
  widm-dashboard-end:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: widm-dashboard-end
    ports:
      - "5173:5173"
    environment:
      - VITE_END_POINT=/dash #no change

      - VITE_API_URL=http://widm.csie.ncu.edu.tw/api #根據nginx設定 遷域名 /api 設為後端
      - VITE_REDIRECT_URI=http://widm.csie.ncu.edu.tw/api/auth/return-to #nginx設定域名/api/auth/return-to 
      - VITE_CLIENT_ID=20241224114804R6cxm7M4T8gP #protol oauth client id

      - VITE_AUTHORITY=https://portal.ncu.edu.tw #protol 自帶參數
      - VITE_TOKEN_ENDPOINT=https://portal.ncu.edu.tw/oauth2/token #protol 自帶參數
      - VITE_AUTHORIZATION_ENDPOINT=https://portal.ncu.edu.tw/oauth2/authorization #protol 自帶參數
      - VITE_USERINFO_ENDPOINT=https://portal.ncu.edu.tw/apis/oauth/v1/info #protol 自帶參數
      
      - VITE_WEB_URL=http://widm.csie.ncu.edu.tw/ #域名
      - VITE_DASHBOARD_URL=http://widm.csie.ncu.edu.tw/dash/ #域名/dash網址
    networks:
      - nginx_proxy
      - backend_network
      - elasticsearch_elastic  # 連接到 Elasticsearch 網路

  widm-front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: widm-front-end
    ports:
      - "7230:7230"
      - "24678:24678"
    environment:
      - NEXT_PUBLIC_API_URL=https://widm.csie.ncu.edu.tw/api
    networks:
      - nginx_proxy
      - backend_network
      - elasticsearch_elastic  # 如果前端需要訪問 Elasticsearch

  widm-backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: widm-back-end
    environment:
      SQLALCHEMY_DATABASE_URI: mysql+pymysql://widm:widmwidm@widm-database:3306/backend
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      BASIC_AUTH: MjAyNDEyMjQxMTQ4MDRSNmN4bTdNNFQ4Z1A6TUE1UnNvTk9ZcmZIeDN0TWY0T0p3VHQ5bnJCdHkweHAzVDVmbHlIcThvZW14akZhcmc1MDJ4
      DASH_BOARD_URL: http://widm.csie.ncu.edu.tw/dash/
      HOME_PAGE_URL: http://widm.csie.ncu.edu.tw
      # Elasticsearch 配置
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
    ports:
      - "5025:5025"
    volumes:
      - ./statics:/app/statics
      - ./instance:/app/instance
      - ./taxonomy_KG2_total_parts_all.json:/app/taxonomy_KG2_total_parts_all.json
    depends_on:
      widm-database:
        condition: service_healthy
    restart: always
    networks:
      - nginx_proxy
      - backend_network
      - elasticsearch_elastic  # 連接到 Elasticsearch 網路

  widm-database:
    image: mysql:8
    container_name: widm-database
    environment:
      MYSQL_ROOT_PASSWORD: widmwidm
      MYSQL_DATABASE: backend
      MYSQL_USER: widm
      MYSQL_PASSWORD: widmwidm
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "widm", "-pwidmwidm" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - backend_network

  widm-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: widm-phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: widm-database
      MYSQL_ROOT_PASSWORD: widmwidm
    restart: always
    networks:
      - nginx_proxy
      - backend_network

networks:
  nginx_proxy:
    external: true
  backend_network:
    internal: true
  elasticsearch_elastic:
    external: true

volumes:
  mysql_data:
